FROM ipfs/go-ipfs
# 
## Specify the command to run when the container starts
CMD ["daemon", "--enable-pubsub-experiment", "--enable-namesys-pubsub", "--routing=dhtclient"]
# Use the official Ubuntu base image
#FROM ubuntu:latest
#
## Install any necessary packages or dependencies for your programs
## For example:
#RUN apt-get update && apt-get install -y curl
#
## Expose port 5001
#EXPOSE 5001
#
## Set a volume for persistent data
#VOLUME /data
#
#CMD ["tail", "-f", "/dev/null"]

